Back 8-9-14-15
Code-the-Dream-School/bb-practicum-team-1-back pull request #20
Opened 2023-03-19 07:09 UTC by Manizha-khorram

In this pull request, I worked on multi tickets. I created book schema, created a a route with authentication for book controller which user can create a book, can view all books related to the user. I also create delete book route because I need it to solve a bug.
the second route I created it without authentication, user can search for single book. all users can view all books list. I added filtering functionality by using quarry parameter. User can search at books list by author name and title of the book, user can Sort books, Select special fields to display, limit number of books wanted to show at one page, determine the page number to show, and skip some books!

2023-03-20 21:16 UTC, jpremo requested changes
This looks pretty good overall. Nice Work. I have several small change requests. The only large request I have is to fit all of these routes into a single API. By that I mean anything at /book should be moved to /books. Some of the routes would need to be changed. For example:

- POST /book => POST /books
- GET /book => GET /books/:userId
- GET /book/image/:id => GET /books/image/:id
- DELETE /book/:id => DELETE /books/:id

2023-03-20 21:16 UTC, jpremo commented on src/controllers/bookController.js
> +    }
Can you update this message to be about books rather than artCollectible?

2023-03-22 13:35 UTC, jpremo commented on src/controllers/user.js
> +    const token = user.createJWT()
This has been addressed in a separate PR.

2023-03-22 22:53 UTC, jpremo requested changes

2023-03-22 22:53 UTC, jpremo commented on models/Book.js
> +            default: 15,
Still need to remove this default

2023-03-22 22:53 UTC, jpremo commented on models/Book.js
> +        },
We don't actually need to include userName in the model. Rather for the queries can you populate the userName based on the userId. Check documentation [here](https://mongoosejs.com/docs/populate.html#field-selection)

2023-03-23 13:41 UTC, jpremo approved these changes
Nice work on this. Before you merge can you populate the username for the book for getSingleBook? Should just be an extra line or two. Feel free to merge afterwards.

2023-03-23 17:22 UTC, Manizha-khorram commented
> Nice work on this. Before you merge can you populate the username for the book for getSingleBook? Should just be an extra line or two. Feel free to merge afterwards.

Thanks a lot Jacob, will do.

2023-03-23 17:38 UTC, merged