Back 63
Code-the-Dream-School/bb-practicum-team-1-back pull request #75
Opened 2023-04-22 06:16 UTC by Manizha-khorram

Sending the message to the user.

2023-04-22 07:19 UTC, larasodjati commented on src/socket.js
> +const { default: mongoose } = require('mongoose')
Nice job Manizha! could you please let me know why do we need mongoose in socket.js?

2023-04-22 07:21 UTC, larasodjati commented
I tested it on Postman, and I believe the code working for sending the message, @jpremo could you please review it as well? Thank you!
<img width="932" alt="image" src="https://user-images.githubusercontent.com/108501073/233769582-a15ed829-3ee5-40c2-9f8a-62a1257c2806.png">

2023-04-22 14:33 UTC, jpremo requested changes
I think this change breaks the POST /messages route. I looked into what I mentioned last night and it does seem possible to emit socketio events in response to HTTP requests. Essentially the goal would be to upon receiving a request at POST /messages send the newly created message to receivedByUser's socket (assuming it exists).

The tricky part of this is getting access to the io object with our current app/server setup. I created a basic example [here](https://github.com/Code-the-Dream-School/bb-practicum-team-1-back/tree/BACK-63-alt-example) that shows one way to accomplish this. I'm sure there are different ways to do the same thing that might be a bit more organized.

Let me know if you have questions or if these requests don't make sense.

2023-04-25 03:43 UTC, larasodjati commented
You did an excellent job with the changes Manizha! I learned a lot from this PR. 
Hi @jpremo, we need your review and approval on this. Thank you!

2023-04-26 04:47 UTC, larasodjati approved these changes

2023-04-27 16:59 UTC, jpremo approved these changes

2023-04-28 17:01 UTC, merged